# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "vmd"
    "nvme"
    "usbhid"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/864b1287-89fd-4cc0-98a5-40a3caf804c6";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  boot.initrd.luks.devices."luks-5fd4fc76-d5c5-46c3-b952-1a7a7ff3a1fc".device =
    "/dev/disk/by-uuid/5fd4fc76-d5c5-46c3-b952-1a7a7ff3a1fc";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2429-4141";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-01571e4eda2f.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-20785fae249b.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-64a49a5722c1.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-71e5fc5962fc.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-7df9905783da.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-9b746f4e7e2f.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-e2f470a56dfe.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u4u4.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth4e96b46.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth96a5ccd.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkForce "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
