---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- System:
    - Fritz!Box:
        name: Fritz!Box
        icon: avmfritzbox.png
        href: http://192.168.178.1
        description: Home router configuration
        widget:
          type: "fritzbox"
          url: http://192.168.178.1
        ping: http://192.168.178.1
