---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- resources:
    label: System
    cpu: true
    memory: true
    uptime: true
    units: metric

- resources:
    label: Storage
    disk: /

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: long
      hourCycle: h23
      locale: de
