name: "Nix: check for unused code"

on:
  pull_request:
  push:
    paths:
      - "**.nix"
      - ".github/workflows/deadnix.yml"

jobs:
  deadnix:
    name: Run deadnix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          persist-credentials: false

      - name: Install lix
        uses: ./.github/actions/install-lix

      - uses: cachix/cachix-action@v14
        with:
          name: deadnix

      - uses: phucleeuwu/deadnix-action@v1
